import re

def format_report(raw_output: str) -> str:
    return f"""
### 🔍 Fraud Investigation Report

{raw_output}

---
*Generated by AI Fraud Investigation Agent*
"""

def extract_risk_level(report: str) -> str:
    """Try to extract risk level from report text."""
    report_upper = report.upper()
    if "CRITICAL" in report_upper:
        return "CRITICAL"
    elif "HIGH" in report_upper:
        return "HIGH"
    elif "MEDIUM" in report_upper:
        return "MEDIUM"
    elif "LOW" in report_upper:
        return "LOW"
    elif "BLOCK" in report_upper:
        return "HIGH"
    elif "REVIEW" in report_upper:
        return "MEDIUM"
    elif "APPROVE" in report_upper:
        return "LOW"
    return "UNKNOWN"

def extract_risk_score(report: str) -> int:
    """Try to extract numeric risk score (0-100)."""
    match = re.search(r"(?:score|risk score)[^\d]*(\d{1,3})", report, re.IGNORECASE)
    if match:
        score = int(match.group(1))
        return min(max(score, 0), 100)
    return 50  # default